### PR TITLE
Vectorise

### PR DESCRIPTION
**Pull request by felixpatzelt**
Separate branch to add tests, maximise readability, and fix minor bugs in @atspaeth 's original implementation of the vectorisation.

### CODE REVIEW

**Comment by atspaeth** [comment]
You don't have a conjugate-symmetric spectrum, so the component with frequency 0.5 is truncated, which means that the real part of the output of the IFFT has too little variance in the even case. The effect is most visible for small even-length sequences of white noise: `cn.powerlaw_psd_gaussian(0, (10**5,10)).var(axis=1).mean()` is about 0.85, while if you replace 10 with 11, it works fine.

Re: the bug you found in the other PR, my fix worked and is pushed to my fork.

**Comment by felixpatzelt** [comment]
Thanks, the 0.5 frequency fix somehow got lost. I tried to clean everything up a bit to make the code as understandable as possible (by my subjective standard), so it is easier to see if everything is correct. I also added another test specifically for very small sample odd and even sample sizes.

**Comment by felixpatzelt** [comment]
Looks all good to me now, will merge in a few days if no new issues come up.

**Comment by atspaeth** [comment]
Yeah, it looks good! I haven't had a chance to test it much yet, but it's much cleaner now and looks correct.

**Pull request merged**
