### PR TITLE
Modified to support generating multiple independent noise series

### PR DESCRIPTION
**Pull request by atspaeth**
I needed to generate many sequences of pink noise at once, so I vectorized your function. Here's an example and a plot of PSD.

```python3
from scipy import signal
import colorednoise as cn
pinks = cn.powerlaw_psd_gaussian(exponent=1, size=(1000,2001), fmin=0.05)
freqs, psd = signal.welch(pinks)

plt.figure(figsize=(5, 4))
plt.loglog(freqs, psd.T, alpha=0.5)
```

pink-noise

### CODE REVIEW

**Comment by felixpatzelt** [comment]
Thanks!

**Comment by atspaeth** [comment]
That is definitely a bug, nice catch! It seems less biased the longer the sequence and the higher you set $f_{\text{min}}$, but it's still there. I think I see where the calculation went wrong, though.

**Comment by atspaeth** [comment]
I think I fixed it. I was overestimating the standard deviation because the DC component shouldn't contribute and I was double-counting the 0.5 component for even sample lengths.

**Comment by felixpatzelt** [comment]
There still are still issues in`8708595`, the first and last series in a batch have the wrong variance:
```python
import colorednoise as cn
y = cn.powerlaw_psd_gaussian(exponent=1, size=(10,2**18))
v = y.var(axis=1)
print(v.round(2))
```
I have a local version which seems to be correct now. I'm merging to a separate branch and then I will try to put the pieces together.

**Comment by atspaeth** [comment]
Oops! I think it's fixed if you replace `si[-1] = 0` and `si[0] = 0` (which are definitely wrong) with `si[...,-1] = 0` and `si[...,0] = 0`. Is that what you're doing too?

**Comment by felixpatzelt** [comment]
I kept the code more similar to the original one and it seems to be correct. Maybe you could try it out, too: https://github.com/felixpatzelt/colorednoise/pull/3

**Pull request merged**
